### ISSUE TITLE
bug: transfer_strata fails to compile on main after #50/#51 — current_query_type unresolved

### ISSUE THREAD

**Issue by Jannich123** [Jannich123/GIRTool_Tauri#53]
## Summary
`src-tauri/src/commands/strata.rs:1010` calls `current_query_type(&state)` inside `transfer_strata`, but the `current_query_type` import was removed earlier when other strata functions were migrated to per-DB `lookup_sql(... &d.query_type)` (PR #51). Build fails:

```
error[E0425]: cannot find function `current_query_type` in this scope
   --> src\commands\strata.rs:1010:14
```

## Fix
`transfer_strata` is still single-DB (its `cfg` is obtained from `state.db.lock()` — the legacy primary connection). Use that DB's own `query_type` field directly:

```rust
// before
let qt = current_query_type(&state);
let template = lookup_sql(&folder, SECTION_STRATA_DOWNLOAD, &qt)
    .unwrap_or_else(|| DATA_SQL.to_string());

// after
let template = lookup_sql(&folder, SECTION_STRATA_DOWNLOAD, &cfg.query_type)
    .unwrap_or_else(|| DATA_SQL.to_string());
```

## Verification
- `cd src-tauri && cargo check` — clean (4 pre-existing warnings allowed, no new errors/warnings).
